//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comdiv.MVC.Resources {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class ControllerRuleStrings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ControllerRuleStrings defaultInstance = ((ControllerRuleStrings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ControllerRuleStrings())));
        
        public static ControllerRuleStrings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mvc_context_descriptor")]
        public string Context_MvcContext {
            get {
                return ((string)(this["Context_MvcContext"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mvc_rules_result")]
        public string Context_Result {
            get {
                return ((string)(this["Context_Result"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("area")]
        public string Xml_Area {
            get {
                return ((string)(this["Xml_Area"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("controller")]
        public string Xml_Controller {
            get {
                return ((string)(this["Xml_Controller"]));
            }
        }
    }
}
