//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comdiv.MVC.Resources {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class IoCNames : global::System.Configuration.ApplicationSettingsBase {
        
        private static IoCNames defaultInstance = ((IoCNames)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new IoCNames())));
        
        public static IoCNames Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("comdiv.mvc.report.defaultrequestloader")]
        public string Report_DefaultLoader {
            get {
                return ((string)(this["Report_DefaultLoader"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("comdiv.mvc.report.defaultrequestinitiator")]
        public string Report_DefaultInitiator {
            get {
                return ((string)(this["Report_DefaultInitiator"]));
            }
        }
    }
}
