//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comdiv.MVC {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class MvcConstants : global::System.Configuration.ApplicationSettingsBase {
        
        private static MvcConstants defaultInstance = ((MvcConstants)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MvcConstants())));
        
        public static MvcConstants Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("persister.default.chain.implementation")]
        public string DefaultPersistenceChainImplementationIoCName {
            get {
                return ((string)(this["DefaultPersistenceChainImplementationIoCName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Comdiv.Inversion.WindsorInversionContainerFactory, Comdiv.MVC")]
        public string DefaultContainerFactory {
            get {
                return ((string)(this["DefaultContainerFactory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?i)[\\r\\n]+[^\\S\\r\\n]*go(?=[^\\S\\r\\n]*?(([\\r\\n]+)|$))")]
        public string DefaultSqlScriptSplitRegex {
            get {
                return ((string)(this["DefaultSqlScriptSplitRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("schema.{0}.sql")]
        public string DefaultScriptMask {
            get {
                return ((string)(this["DefaultScriptMask"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultWindsorFileName {
            get {
                return ((string)(this["DefaultWindsorFileName"]));
            }
        }
    }
}
